// DO NOT EDIT
// This file was @generated by Stone

#![allow(
    dead_code,
    clippy::too_many_arguments,
    clippy::too_many_arguments,
    clippy::large_enum_variant,
    clippy::result_large_err,
    clippy::doc_markdown
)]

#[allow(unused_imports)]
use base64::{Engine as _, engine::general_purpose::STANDARD_NO_PAD as BASE64};

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct BootArg {
    pub pub_key_id: String,
    pub pub_key: String,
}

impl BootArg {
    pub fn new(pub_key_id: String, pub_key: String) -> Self {
        BootArg {
            pub_key_id,
            pub_key,
        }
    }
}

const BOOT_ARG_FIELDS: &[&str] = &["pub_key_id", "pub_key"];
impl BootArg {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<BootArg, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<BootArg>, V::Error> {
        let mut field_pub_key_id = None;
        let mut field_pub_key = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "pub_key_id" => {
                    if field_pub_key_id.is_some() {
                        return Err(::serde::de::Error::duplicate_field("pub_key_id"));
                    }
                    field_pub_key_id = Some(map.next_value()?);
                }
                "pub_key" => {
                    if field_pub_key.is_some() {
                        return Err(::serde::de::Error::duplicate_field("pub_key"));
                    }
                    field_pub_key = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = BootArg {
            pub_key_id: field_pub_key_id
                .ok_or_else(|| ::serde::de::Error::missing_field("pub_key_id"))?,
            pub_key: field_pub_key.ok_or_else(|| ::serde::de::Error::missing_field("pub_key"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("pub_key_id", &self.pub_key_id)?;
        s.serialize_field("pub_key", &self.pub_key)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for BootArg {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = BootArg;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BootArg struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                BootArg::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("BootArg", BOOT_ARG_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for BootArg {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("BootArg", 2)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // variants may be added in the future
pub enum BootError {
    AlreadyRunning,
    DeployFailed,
    /// Catch-all used for unrecognized values returned from the server. Encountering this value
    /// typically indicates that this SDK version is out of date.
    Other,
}

impl<'de> ::serde::de::Deserialize<'de> for BootError {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // union deserializer
        use serde::de::{self, MapAccess, Visitor};
        struct EnumVisitor;
        impl<'de> Visitor<'de> for EnumVisitor {
            type Value = BootError;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BootError structure")
            }
            fn visit_map<V: MapAccess<'de>>(self, mut map: V) -> Result<Self::Value, V::Error> {
                let tag: &str = match map.next_key()? {
                    Some(".tag") => map.next_value()?,
                    _ => return Err(de::Error::missing_field(".tag")),
                };
                let value = match tag {
                    "already_running" => BootError::AlreadyRunning,
                    "deploy_failed" => BootError::DeployFailed,
                    _ => BootError::Other,
                };
                super::eat_json_fields(&mut map)?;
                Ok(value)
            }
        }
        const VARIANTS: &[&str] = &["already_running", "deploy_failed", "other"];
        deserializer.deserialize_struct("BootError", VARIANTS, EnumVisitor)
    }
}

impl ::serde::ser::Serialize for BootError {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // union serializer
        use serde::ser::SerializeStruct;
        match *self {
            BootError::AlreadyRunning => {
                // unit
                let mut s = serializer.serialize_struct("BootError", 1)?;
                s.serialize_field(".tag", "already_running")?;
                s.end()
            }
            BootError::DeployFailed => {
                // unit
                let mut s = serializer.serialize_struct("BootError", 1)?;
                s.serialize_field(".tag", "deploy_failed")?;
                s.end()
            }
            BootError::Other => Err(::serde::ser::Error::custom(
                "cannot serialize 'Other' variant",
            )),
        }
    }
}

impl ::std::error::Error for BootError {}

impl ::std::fmt::Display for BootError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "{:?}", *self)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct BootResult {
    pub bot: BotInfo,
}

impl BootResult {
    pub fn new(bot: BotInfo) -> Self {
        BootResult { bot }
    }
}

const BOOT_RESULT_FIELDS: &[&str] = &["bot"];
impl BootResult {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<BootResult, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<BootResult>, V::Error> {
        let mut field_bot = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "bot" => {
                    if field_bot.is_some() {
                        return Err(::serde::de::Error::duplicate_field("bot"));
                    }
                    field_bot = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = BootResult {
            bot: field_bot.ok_or_else(|| ::serde::de::Error::missing_field("bot"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("bot", &self.bot)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for BootResult {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = BootResult;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BootResult struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                BootResult::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("BootResult", BOOT_RESULT_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for BootResult {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("BootResult", 1)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct BotInfo {
    pub bot_id: String,
    pub hostname: String,
    pub booted_at: super::common::UtcTimestamp,
    pub terminated_at: Option<super::common::UtcTimestamp>,
}

impl BotInfo {
    pub fn new(bot_id: String, hostname: String, booted_at: super::common::UtcTimestamp) -> Self {
        BotInfo {
            bot_id,
            hostname,
            booted_at,
            terminated_at: None,
        }
    }

    pub fn with_terminated_at(mut self, value: super::common::UtcTimestamp) -> Self {
        self.terminated_at = Some(value);
        self
    }
}

const BOT_INFO_FIELDS: &[&str] = &["bot_id", "hostname", "booted_at", "terminated_at"];
impl BotInfo {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<BotInfo, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<BotInfo>, V::Error> {
        let mut field_bot_id = None;
        let mut field_hostname = None;
        let mut field_booted_at = None;
        let mut field_terminated_at = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "bot_id" => {
                    if field_bot_id.is_some() {
                        return Err(::serde::de::Error::duplicate_field("bot_id"));
                    }
                    field_bot_id = Some(map.next_value()?);
                }
                "hostname" => {
                    if field_hostname.is_some() {
                        return Err(::serde::de::Error::duplicate_field("hostname"));
                    }
                    field_hostname = Some(map.next_value()?);
                }
                "booted_at" => {
                    if field_booted_at.is_some() {
                        return Err(::serde::de::Error::duplicate_field("booted_at"));
                    }
                    field_booted_at = Some(map.next_value()?);
                }
                "terminated_at" => {
                    if field_terminated_at.is_some() {
                        return Err(::serde::de::Error::duplicate_field("terminated_at"));
                    }
                    field_terminated_at = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = BotInfo {
            bot_id: field_bot_id.ok_or_else(|| ::serde::de::Error::missing_field("bot_id"))?,
            hostname: field_hostname
                .ok_or_else(|| ::serde::de::Error::missing_field("hostname"))?,
            booted_at: field_booted_at
                .ok_or_else(|| ::serde::de::Error::missing_field("booted_at"))?,
            terminated_at: field_terminated_at.and_then(Option::flatten),
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("bot_id", &self.bot_id)?;
        s.serialize_field("hostname", &self.hostname)?;
        s.serialize_field("booted_at", &self.booted_at)?;
        if let Some(val) = &self.terminated_at {
            s.serialize_field("terminated_at", val)?;
        }
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for BotInfo {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = BotInfo;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BotInfo struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                BotInfo::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("BotInfo", BOT_INFO_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for BotInfo {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("BotInfo", 4)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct GetActiveResult {
    pub bot: Option<BotInfo>,
}

impl GetActiveResult {
    pub fn with_bot(mut self, value: BotInfo) -> Self {
        self.bot = Some(value);
        self
    }
}

const GET_ACTIVE_RESULT_FIELDS: &[&str] = &["bot"];
impl GetActiveResult {
    // no _opt deserializer
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
    ) -> Result<GetActiveResult, V::Error> {
        let mut field_bot = None;
        while let Some(key) = map.next_key::<&str>()? {
            match key {
                "bot" => {
                    if field_bot.is_some() {
                        return Err(::serde::de::Error::duplicate_field("bot"));
                    }
                    field_bot = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        let result = GetActiveResult {
            bot: field_bot.and_then(Option::flatten),
        };
        Ok(result)
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        if let Some(val) = &self.bot {
            s.serialize_field("bot", val)?;
        }
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for GetActiveResult {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = GetActiveResult;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a GetActiveResult struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                GetActiveResult::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("GetActiveResult", GET_ACTIVE_RESULT_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for GetActiveResult {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("GetActiveResult", 1)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct GetArg {
    pub bot_id: String,
}

impl GetArg {
    pub fn new(bot_id: String) -> Self {
        GetArg { bot_id }
    }
}

const GET_ARG_FIELDS: &[&str] = &["bot_id"];
impl GetArg {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<GetArg, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<GetArg>, V::Error> {
        let mut field_bot_id = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "bot_id" => {
                    if field_bot_id.is_some() {
                        return Err(::serde::de::Error::duplicate_field("bot_id"));
                    }
                    field_bot_id = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = GetArg {
            bot_id: field_bot_id.ok_or_else(|| ::serde::de::Error::missing_field("bot_id"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("bot_id", &self.bot_id)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for GetArg {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = GetArg;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a GetArg struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                GetArg::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("GetArg", GET_ARG_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for GetArg {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("GetArg", 1)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // variants may be added in the future
pub enum GetError {
    BadBotId,
    /// Catch-all used for unrecognized values returned from the server. Encountering this value
    /// typically indicates that this SDK version is out of date.
    Other,
}

impl<'de> ::serde::de::Deserialize<'de> for GetError {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // union deserializer
        use serde::de::{self, MapAccess, Visitor};
        struct EnumVisitor;
        impl<'de> Visitor<'de> for EnumVisitor {
            type Value = GetError;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a GetError structure")
            }
            fn visit_map<V: MapAccess<'de>>(self, mut map: V) -> Result<Self::Value, V::Error> {
                let tag: &str = match map.next_key()? {
                    Some(".tag") => map.next_value()?,
                    _ => return Err(de::Error::missing_field(".tag")),
                };
                let value = match tag {
                    "bad_bot_id" => GetError::BadBotId,
                    _ => GetError::Other,
                };
                super::eat_json_fields(&mut map)?;
                Ok(value)
            }
        }
        const VARIANTS: &[&str] = &["bad_bot_id", "other"];
        deserializer.deserialize_struct("GetError", VARIANTS, EnumVisitor)
    }
}

impl ::serde::ser::Serialize for GetError {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // union serializer
        use serde::ser::SerializeStruct;
        match *self {
            GetError::BadBotId => {
                // unit
                let mut s = serializer.serialize_struct("GetError", 1)?;
                s.serialize_field(".tag", "bad_bot_id")?;
                s.end()
            }
            GetError::Other => Err(::serde::ser::Error::custom(
                "cannot serialize 'Other' variant",
            )),
        }
    }
}

impl ::std::error::Error for GetError {}

impl ::std::fmt::Display for GetError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "{:?}", *self)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct GetResult {
    pub bot: BotInfo,
}

impl GetResult {
    pub fn new(bot: BotInfo) -> Self {
        GetResult { bot }
    }
}

const GET_RESULT_FIELDS: &[&str] = &["bot"];
impl GetResult {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<GetResult, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<GetResult>, V::Error> {
        let mut field_bot = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "bot" => {
                    if field_bot.is_some() {
                        return Err(::serde::de::Error::duplicate_field("bot"));
                    }
                    field_bot = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = GetResult {
            bot: field_bot.ok_or_else(|| ::serde::de::Error::missing_field("bot"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("bot", &self.bot)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for GetResult {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = GetResult;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a GetResult struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                GetResult::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("GetResult", GET_RESULT_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for GetResult {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("GetResult", 1)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct ShutdownArg {
    pub bot_id: String,
}

impl ShutdownArg {
    pub fn new(bot_id: String) -> Self {
        ShutdownArg { bot_id }
    }
}

const SHUTDOWN_ARG_FIELDS: &[&str] = &["bot_id"];
impl ShutdownArg {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<ShutdownArg, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<ShutdownArg>, V::Error> {
        let mut field_bot_id = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "bot_id" => {
                    if field_bot_id.is_some() {
                        return Err(::serde::de::Error::duplicate_field("bot_id"));
                    }
                    field_bot_id = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = ShutdownArg {
            bot_id: field_bot_id.ok_or_else(|| ::serde::de::Error::missing_field("bot_id"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("bot_id", &self.bot_id)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for ShutdownArg {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = ShutdownArg;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a ShutdownArg struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                ShutdownArg::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("ShutdownArg", SHUTDOWN_ARG_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for ShutdownArg {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("ShutdownArg", 1)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // variants may be added in the future
pub enum ShutdownError {
    BadBotId,
    Failed,
    AlreadyShutdown,
    /// Catch-all used for unrecognized values returned from the server. Encountering this value
    /// typically indicates that this SDK version is out of date.
    Other,
}

impl<'de> ::serde::de::Deserialize<'de> for ShutdownError {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // union deserializer
        use serde::de::{self, MapAccess, Visitor};
        struct EnumVisitor;
        impl<'de> Visitor<'de> for EnumVisitor {
            type Value = ShutdownError;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a ShutdownError structure")
            }
            fn visit_map<V: MapAccess<'de>>(self, mut map: V) -> Result<Self::Value, V::Error> {
                let tag: &str = match map.next_key()? {
                    Some(".tag") => map.next_value()?,
                    _ => return Err(de::Error::missing_field(".tag")),
                };
                let value = match tag {
                    "bad_bot_id" => ShutdownError::BadBotId,
                    "failed" => ShutdownError::Failed,
                    "already_shutdown" => ShutdownError::AlreadyShutdown,
                    _ => ShutdownError::Other,
                };
                super::eat_json_fields(&mut map)?;
                Ok(value)
            }
        }
        const VARIANTS: &[&str] = &["bad_bot_id", "failed", "already_shutdown", "other"];
        deserializer.deserialize_struct("ShutdownError", VARIANTS, EnumVisitor)
    }
}

impl ::serde::ser::Serialize for ShutdownError {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // union serializer
        use serde::ser::SerializeStruct;
        match *self {
            ShutdownError::BadBotId => {
                // unit
                let mut s = serializer.serialize_struct("ShutdownError", 1)?;
                s.serialize_field(".tag", "bad_bot_id")?;
                s.end()
            }
            ShutdownError::Failed => {
                // unit
                let mut s = serializer.serialize_struct("ShutdownError", 1)?;
                s.serialize_field(".tag", "failed")?;
                s.end()
            }
            ShutdownError::AlreadyShutdown => {
                // unit
                let mut s = serializer.serialize_struct("ShutdownError", 1)?;
                s.serialize_field(".tag", "already_shutdown")?;
                s.end()
            }
            ShutdownError::Other => Err(::serde::ser::Error::custom(
                "cannot serialize 'Other' variant",
            )),
        }
    }
}

impl ::std::error::Error for ShutdownError {}

impl ::std::fmt::Display for ShutdownError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "{:?}", *self)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct ShutdownResult {
    pub bot: BotInfo,
}

impl ShutdownResult {
    pub fn new(bot: BotInfo) -> Self {
        ShutdownResult { bot }
    }
}

const SHUTDOWN_RESULT_FIELDS: &[&str] = &["bot"];
impl ShutdownResult {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<ShutdownResult, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<ShutdownResult>, V::Error> {
        let mut field_bot = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "bot" => {
                    if field_bot.is_some() {
                        return Err(::serde::de::Error::duplicate_field("bot"));
                    }
                    field_bot = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = ShutdownResult {
            bot: field_bot.ok_or_else(|| ::serde::de::Error::missing_field("bot"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("bot", &self.bot)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for ShutdownResult {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = ShutdownResult;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a ShutdownResult struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                ShutdownResult::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("ShutdownResult", SHUTDOWN_RESULT_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for ShutdownResult {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("ShutdownResult", 1)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}
