// DO NOT EDIT
// This file was @generated by Stone

#![allow(
    dead_code,
    clippy::too_many_arguments,
    clippy::too_many_arguments,
    clippy::large_enum_variant,
    clippy::result_large_err,
    clippy::doc_markdown
)]

#[allow(unused_imports)]
use base64::{Engine as _, engine::general_purpose::STANDARD_NO_PAD as BASE64};

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // variants may be added in the future
pub enum BraveFreshness {
    /// Past 24 hours
    Pd,
    /// Past 7 days
    Pw,
    /// Past 31 days
    Pm,
    /// Past year
    Py,
    /// Custom date range. Example: 2022-04-01to2022-07-30
    Custom(String),
    /// Catch-all used for unrecognized values returned from the server. Encountering this value
    /// typically indicates that this SDK version is out of date.
    Other,
}

impl<'de> ::serde::de::Deserialize<'de> for BraveFreshness {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // union deserializer
        use serde::de::{self, MapAccess, Visitor};
        struct EnumVisitor;
        impl<'de> Visitor<'de> for EnumVisitor {
            type Value = BraveFreshness;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BraveFreshness structure")
            }
            fn visit_map<V: MapAccess<'de>>(self, mut map: V) -> Result<Self::Value, V::Error> {
                let tag: &str = match map.next_key()? {
                    Some(".tag") => map.next_value()?,
                    _ => return Err(de::Error::missing_field(".tag")),
                };
                let value = match tag {
                    "pd" => BraveFreshness::Pd,
                    "pw" => BraveFreshness::Pw,
                    "pm" => BraveFreshness::Pm,
                    "py" => BraveFreshness::Py,
                    "custom" => match map.next_key()? {
                        Some("custom") => BraveFreshness::Custom(map.next_value()?),
                        None => return Err(de::Error::missing_field("custom")),
                        _ => return Err(de::Error::unknown_field(tag, VARIANTS)),
                    },
                    _ => BraveFreshness::Other,
                };
                super::eat_json_fields(&mut map)?;
                Ok(value)
            }
        }
        const VARIANTS: &[&str] = &["pd", "pw", "pm", "py", "custom", "other"];
        deserializer.deserialize_struct("BraveFreshness", VARIANTS, EnumVisitor)
    }
}

impl ::serde::ser::Serialize for BraveFreshness {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // union serializer
        use serde::ser::SerializeStruct;
        match *self {
            BraveFreshness::Pd => {
                // unit
                let mut s = serializer.serialize_struct("BraveFreshness", 1)?;
                s.serialize_field(".tag", "pd")?;
                s.end()
            }
            BraveFreshness::Pw => {
                // unit
                let mut s = serializer.serialize_struct("BraveFreshness", 1)?;
                s.serialize_field(".tag", "pw")?;
                s.end()
            }
            BraveFreshness::Pm => {
                // unit
                let mut s = serializer.serialize_struct("BraveFreshness", 1)?;
                s.serialize_field(".tag", "pm")?;
                s.end()
            }
            BraveFreshness::Py => {
                // unit
                let mut s = serializer.serialize_struct("BraveFreshness", 1)?;
                s.serialize_field(".tag", "py")?;
                s.end()
            }
            BraveFreshness::Custom(ref x) => {
                // primitive
                let mut s = serializer.serialize_struct("BraveFreshness", 2)?;
                s.serialize_field(".tag", "custom")?;
                s.serialize_field("custom", x)?;
                s.end()
            }
            BraveFreshness::Other => Err(::serde::ser::Error::custom(
                "cannot serialize 'Other' variant",
            )),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct BraveGrounding {
    pub generic: Vec<BraveSearchHit>,
}

impl BraveGrounding {
    pub fn new(generic: Vec<BraveSearchHit>) -> Self {
        BraveGrounding { generic }
    }
}

const BRAVE_GROUNDING_FIELDS: &[&str] = &["generic"];
impl BraveGrounding {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<BraveGrounding, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<BraveGrounding>, V::Error> {
        let mut field_generic = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "generic" => {
                    if field_generic.is_some() {
                        return Err(::serde::de::Error::duplicate_field("generic"));
                    }
                    field_generic = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = BraveGrounding {
            generic: field_generic.ok_or_else(|| ::serde::de::Error::missing_field("generic"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("generic", &self.generic)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for BraveGrounding {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = BraveGrounding;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BraveGrounding struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                BraveGrounding::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("BraveGrounding", BRAVE_GROUNDING_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for BraveGrounding {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("BraveGrounding", 1)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct BraveSearchArg {
    /// Web search query. Additional parameters include: Use quotes for exact phrase matching:
    /// "climate change solutions" Exclude terms with minus: javascript -jquery Site-specific
    /// searches: site:github.com rust tutorials File type searches: filetype:pdf machine learning
    pub q: String,
    pub count: u32,
    pub freshness: Option<BraveFreshness>,
}

impl BraveSearchArg {
    pub fn new(q: String) -> Self {
        BraveSearchArg {
            q,
            count: 5,
            freshness: None,
        }
    }

    pub fn with_count(mut self, value: u32) -> Self {
        self.count = value;
        self
    }

    pub fn with_freshness(mut self, value: BraveFreshness) -> Self {
        self.freshness = Some(value);
        self
    }
}

const BRAVE_SEARCH_ARG_FIELDS: &[&str] = &["q", "count", "freshness"];
impl BraveSearchArg {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<BraveSearchArg, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<BraveSearchArg>, V::Error> {
        let mut field_q = None;
        let mut field_count = None;
        let mut field_freshness = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "q" => {
                    if field_q.is_some() {
                        return Err(::serde::de::Error::duplicate_field("q"));
                    }
                    field_q = Some(map.next_value()?);
                }
                "count" => {
                    if field_count.is_some() {
                        return Err(::serde::de::Error::duplicate_field("count"));
                    }
                    field_count = Some(map.next_value()?);
                }
                "freshness" => {
                    if field_freshness.is_some() {
                        return Err(::serde::de::Error::duplicate_field("freshness"));
                    }
                    field_freshness = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = BraveSearchArg {
            q: field_q.ok_or_else(|| ::serde::de::Error::missing_field("q"))?,
            count: field_count.unwrap_or(5),
            freshness: field_freshness.and_then(Option::flatten),
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("q", &self.q)?;
        if self.count != 5 {
            s.serialize_field("count", &self.count)?;
        }
        if let Some(val) = &self.freshness {
            s.serialize_field("freshness", val)?;
        }
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for BraveSearchArg {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = BraveSearchArg;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BraveSearchArg struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                BraveSearchArg::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("BraveSearchArg", BRAVE_SEARCH_ARG_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for BraveSearchArg {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("BraveSearchArg", 3)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // variants may be added in the future
pub enum BraveSearchError {
    BadQ,
    /// The active account has made too many search queries.
    LimitExceeded,
    /// Catch-all used for unrecognized values returned from the server. Encountering this value
    /// typically indicates that this SDK version is out of date.
    Other,
}

impl<'de> ::serde::de::Deserialize<'de> for BraveSearchError {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // union deserializer
        use serde::de::{self, MapAccess, Visitor};
        struct EnumVisitor;
        impl<'de> Visitor<'de> for EnumVisitor {
            type Value = BraveSearchError;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BraveSearchError structure")
            }
            fn visit_map<V: MapAccess<'de>>(self, mut map: V) -> Result<Self::Value, V::Error> {
                let tag: &str = match map.next_key()? {
                    Some(".tag") => map.next_value()?,
                    _ => return Err(de::Error::missing_field(".tag")),
                };
                let value = match tag {
                    "bad_q" => BraveSearchError::BadQ,
                    "limit_exceeded" => BraveSearchError::LimitExceeded,
                    _ => BraveSearchError::Other,
                };
                super::eat_json_fields(&mut map)?;
                Ok(value)
            }
        }
        const VARIANTS: &[&str] = &["bad_q", "limit_exceeded", "other"];
        deserializer.deserialize_struct("BraveSearchError", VARIANTS, EnumVisitor)
    }
}

impl ::serde::ser::Serialize for BraveSearchError {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // union serializer
        use serde::ser::SerializeStruct;
        match *self {
            BraveSearchError::BadQ => {
                // unit
                let mut s = serializer.serialize_struct("BraveSearchError", 1)?;
                s.serialize_field(".tag", "bad_q")?;
                s.end()
            }
            BraveSearchError::LimitExceeded => {
                // unit
                let mut s = serializer.serialize_struct("BraveSearchError", 1)?;
                s.serialize_field(".tag", "limit_exceeded")?;
                s.end()
            }
            BraveSearchError::Other => Err(::serde::ser::Error::custom(
                "cannot serialize 'Other' variant",
            )),
        }
    }
}

impl ::std::error::Error for BraveSearchError {}

impl ::std::fmt::Display for BraveSearchError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            BraveSearchError::LimitExceeded => {
                f.write_str("The active account has made too many search queries.")
            }
            _ => write!(f, "{:?}", *self),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct BraveSearchHit {
    pub url: String,
    pub title: String,
    pub snippets: Vec<String>,
}

impl BraveSearchHit {
    pub fn new(url: String, title: String, snippets: Vec<String>) -> Self {
        BraveSearchHit {
            url,
            title,
            snippets,
        }
    }
}

const BRAVE_SEARCH_HIT_FIELDS: &[&str] = &["url", "title", "snippets"];
impl BraveSearchHit {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<BraveSearchHit, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<BraveSearchHit>, V::Error> {
        let mut field_url = None;
        let mut field_title = None;
        let mut field_snippets = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "url" => {
                    if field_url.is_some() {
                        return Err(::serde::de::Error::duplicate_field("url"));
                    }
                    field_url = Some(map.next_value()?);
                }
                "title" => {
                    if field_title.is_some() {
                        return Err(::serde::de::Error::duplicate_field("title"));
                    }
                    field_title = Some(map.next_value()?);
                }
                "snippets" => {
                    if field_snippets.is_some() {
                        return Err(::serde::de::Error::duplicate_field("snippets"));
                    }
                    field_snippets = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = BraveSearchHit {
            url: field_url.ok_or_else(|| ::serde::de::Error::missing_field("url"))?,
            title: field_title.ok_or_else(|| ::serde::de::Error::missing_field("title"))?,
            snippets: field_snippets
                .ok_or_else(|| ::serde::de::Error::missing_field("snippets"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("url", &self.url)?;
        s.serialize_field("title", &self.title)?;
        s.serialize_field("snippets", &self.snippets)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for BraveSearchHit {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = BraveSearchHit;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BraveSearchHit struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                BraveSearchHit::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct("BraveSearchHit", BRAVE_SEARCH_HIT_FIELDS, StructVisitor)
    }
}

impl ::serde::ser::Serialize for BraveSearchHit {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("BraveSearchHit", 3)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive] // structs may have more fields added in the future.
pub struct BraveSearchResult {
    pub grounding: BraveGrounding,
}

impl BraveSearchResult {
    pub fn new(grounding: BraveGrounding) -> Self {
        BraveSearchResult { grounding }
    }
}

const BRAVE_SEARCH_RESULT_FIELDS: &[&str] = &["grounding"];
impl BraveSearchResult {
    pub(crate) fn internal_deserialize<'de, V: ::serde::de::MapAccess<'de>>(
        map: V,
    ) -> Result<BraveSearchResult, V::Error> {
        Self::internal_deserialize_opt(map, false).map(Option::unwrap)
    }

    pub(crate) fn internal_deserialize_opt<'de, V: ::serde::de::MapAccess<'de>>(
        mut map: V,
        optional: bool,
    ) -> Result<Option<BraveSearchResult>, V::Error> {
        let mut field_grounding = None;
        let mut nothing = true;
        while let Some(key) = map.next_key::<&str>()? {
            nothing = false;
            match key {
                "grounding" => {
                    if field_grounding.is_some() {
                        return Err(::serde::de::Error::duplicate_field("grounding"));
                    }
                    field_grounding = Some(map.next_value()?);
                }
                _ => {
                    // unknown field allowed and ignored
                    map.next_value::<::serde_json::Value>()?;
                }
            }
        }
        if optional && nothing {
            return Ok(None);
        }
        let result = BraveSearchResult {
            grounding: field_grounding
                .ok_or_else(|| ::serde::de::Error::missing_field("grounding"))?,
        };
        Ok(Some(result))
    }

    pub(crate) fn internal_serialize<S: ::serde::ser::Serializer>(
        &self,
        s: &mut S::SerializeStruct,
    ) -> Result<(), S::Error> {
        use serde::ser::SerializeStruct;
        s.serialize_field("grounding", &self.grounding)?;
        Ok(())
    }
}

impl<'de> ::serde::de::Deserialize<'de> for BraveSearchResult {
    fn deserialize<D: ::serde::de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // struct deserializer
        use serde::de::{MapAccess, Visitor};
        struct StructVisitor;
        impl<'de> Visitor<'de> for StructVisitor {
            type Value = BraveSearchResult;
            fn expecting(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str("a BraveSearchResult struct")
            }
            fn visit_map<V: MapAccess<'de>>(self, map: V) -> Result<Self::Value, V::Error> {
                BraveSearchResult::internal_deserialize(map)
            }
        }
        deserializer.deserialize_struct(
            "BraveSearchResult",
            BRAVE_SEARCH_RESULT_FIELDS,
            StructVisitor,
        )
    }
}

impl ::serde::ser::Serialize for BraveSearchResult {
    fn serialize<S: ::serde::ser::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // struct serializer
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("BraveSearchResult", 1)?;
        self.internal_serialize::<S>(&mut s)?;
        s.end()
    }
}
